const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const html = fs.readFileSync(path.join(__dirname, "..", "index.html"), "utf8");
const app = fs.readFileSync(path.join(__dirname, "..", "app.js"), "utf8");
const css = fs.readFileSync(path.join(__dirname, "..", "style.css"), "utf8");

assert.match(html, /id="nsr-map-models"/);
assert.match(html, /id="nsr-map-legend"/);
assert.match(html, /id="nsr-map-insights"/);
assert.match(html, /src="nsr-map\.js(?:\?[^\"]*)?"/);
assert.match(html, /产品评价数据入口/);
assert.match(html, /本品领先与竞品威胁/);
assert.match(html, /id="dashboard-anchor-nav"/);
assert.match(html, /id="dashboard-competitor-intelligence"/);
assert.match(html, /id="dashboard-competitor-trend"/);
assert.doesNotMatch(html, /id="dashboard-evidence-cards"/);
assert.match(html, /id="dashboard-product-proof"/);
assert.match(html, /id="dashboard-strategy-choice"/);
assert.doesNotMatch(html, /id="map-filters"/);
assert.doesNotMatch(html, /id="opportunity-evidence-workbench"/);
assert.doesNotMatch(html, /data-filter="待人工确认"/);
assert.match(app, /function renderDataFirstNsrMap\(/);
assert.match(app, /MmnNsrMap\.buildDataFirstNsrMap/);
assert.match(app, /MmnNsrMap\.rankNsrLabel/);
assert.match(app, /data-nsr-map-detail/);
assert.match(app, /function nsrMapOwnDecisionItems\(/);
assert.match(app, /本品领先/);
assert.match(app, /主要对标/);
assert.match(app, /本品第/);
assert.match(app, /coverageLabel/);
assert.doesNotMatch(app, /灰色代号仅用于识别车型/);
assert.doesNotMatch(app, /function renderDashboardDecisionBrief\(/);
assert.doesNotMatch(app, /function renderDashboardCompetitorSet\(/);
assert.match(app, /function attributeEvidenceStatus\(/);
assert.match(app, /function openSummaryAttributePopover\(/);
assert.match(app, /function renderDashboardCompetitorTrend\(/);
assert.match(app, /function dashboardDistinctCompetitorRows\(/);
assert.match(app, /function nullableNumber\(/);
assert.match(app, /function attributeSourceScores\(/);
assert.match(app, /与上周相比/);
assert.match(app, /不代表偏好、口碑或销量/);
assert.match(app, /暂无环比/);
assert.match(app, /持平/);
assert.match(app, /升至/);
assert.match(app, /降至/);
assert.doesNotMatch(app, /changeText[^;]+pt/);
assert.doesNotMatch(app, /const selectedSource="all"/);
assert.doesNotMatch(app, /const share=Number\(latest\.share\)/);
assert.doesNotMatch(app, /共同对比增强/);
assert.doesNotMatch(app, /共同对比减弱/);
assert.doesNotMatch(app, /function renderDashboardEvidenceCards\(/);
assert.doesNotMatch(app, /NSR × 垂媒合并判断/);
assert.match(app, /function renderDashboardProductProof\(/);
assert.match(app, /function renderDashboardStrategyChoice\(/);
assert.match(app, /function persistDashboardLearningAndKnowhow\(/);
assert.match(app, /data-dashboard-learning/);
assert.match(app, /data-dashboard-knowhow/);
assert.match(app, /data-summary-attribute-model/);
assert.match(app, /来源冲突/);
assert.match(app, /本品与竞品属性对比/);
assert.match(app, /data-nsr-map-close/);
assert.match(app, /本品固定展示/);
assert.match(app, /function syncDashboardCompetitors\(\)\{\s*if\(isBlockedImport\(\)\)[\s\S]{0,250}if\(isSummaryImport\(\)\)/);
assert.doesNotMatch(app, /document\.querySelector\("#map-limit"\)\.onchange/);
assert.match(css, /\.nsr-map-models/);
assert.match(css, /\.nsr-map-legend/);
assert.match(css, /\.bubble\.pending/);
assert.match(css, /\.nsr-map-detail/);
assert.doesNotMatch(css, /\.dashboard-decision-brief/);
assert.doesNotMatch(css, /\.dashboard-competitor-set/);
assert.match(css, /\.summary-attribute-popover/);
assert.match(css, /\.dashboard-anchor-nav/);
assert.match(css, /\.dashboard-competitor-trend/);
assert.match(css, /\.dashboard-evidence-cards/);
assert.match(css, /\.dashboard-strategy-choice/);

console.log("data-first cockpit ui: ok");
