const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'demo-brand-weekly-radar.html'),'utf8');
function renderer(){
 const nodes=new Map();
 const document={querySelector(key){if(!nodes.has(key))nodes.set(key,{innerHTML:'',textContent:'',className:'',replaceChildren(){this.innerHTML=''},addEventListener(){}});return nodes.get(key)},querySelectorAll(){return[]}};
 const context=vm.createContext({document,URL,console,window:{parent:{},addEventListener(){}},Map,Set});
 vm.runInContext(html.slice(html.indexOf('    function safeMartText'),html.indexOf('    function renderBrandPenetrationMart')),context);
 return{context,render(decision){context.renderBrandDecision(decision);return [...nodes.values()].map(n=>n.innerHTML+' '+n.textContent).join('\n')}};
}
const source={claimId:'source',text:'该来源提及新车发布',publicationStatus:'source_only',evidenceRefs:[{evidenceId:'e1',quote:'来源原文',sourceUrl:'https://example.com/source',brand:'本品',publishedAt:'2026-09-01'}]};
function decision(overrides={}){return{schemaVersion:'brand-penetration-analysis-v4',ownBrand:'本品',brandConclusions:[{brand:'本品',status:'source_only',facts:[source],insights:[],actionOptions:[],disputes:[],unknowns:[],evidenceCount:1,independentSourceCount:1,reviewCoverage:{completed:3,required:3},...overrides}],pairwiseConclusions:[]}}
let failed=0,passed=0;
function test(name,fn){try{fn();passed++;console.log('PASS',name)}catch(e){failed++;console.error('FAIL',name,e.message)}}
test('v4 source-only row keeps its independently available fact',()=>{const text=renderer().render(decision());assert.match(text,/该来源提及新车发布/);assert.match(text,/仅展示来源信息/);assert.match(text,/本品/);assert.doesNotMatch(text,/置信度/)});
test('disputed interpretation does not suppress facts or leak raw candidate',()=>{const text=renderer().render(decision({unknowns:[{claimId:'c',publicationStatus:'disputed',text:'待核对',candidateText:'RAW UNSAFE',canonicalCandidateText:'限定来源解释',owner:'项目复核负责人',affectedClaimIds:['c1']}]}));assert.match(text,/来源原文/);assert.match(text,/待确认提案/);assert.match(text,/限定来源解释/);assert.doesNotMatch(text,/RAW UNSAFE/)});
test('full layered output shows independent insight and conditional action',()=>{const text=renderer().render(decision({insights:[{claimId:'i',text:'传播观察',publicationStatus:'supported'}],actionOptions:[{claimId:'a',text:'人工核对来源',publicationStatus:'candidate',allowExecution:false,actionContract:{conditions:'条件',costRisk:'风险',leadingIndicator:'领先',outcomeIndicator:'结果',validationThreshold:'阈值',observationWindow:'窗口',stopCondition:'停止',nonGoals:'不做'}}]}));assert.match(text,/传播观察/);assert.match(text,/人工核对来源/);assert.match(text,/停止/);assert.match(text,/不自动执行/)});
test('incomplete review explicitly stays incomplete while fact remains',()=>{const text=renderer().render(decision({reviewCoverage:{completed:2,required:3},unknowns:[{claimId:'c',text:'待核对',publicationStatus:'review_incomplete'}]}));assert.match(text,/复核未完成/);assert.match(text,/2\/3/);assert.match(text,/该来源提及/)});
test('v3 has history label and leaves stored body untouched',()=>{const d={schemaVersion:'brand-penetration-analysis-v3',brandConclusions:[{brand:'历史',status:'aligned',conclusion:'历史原文',confidence:.8}],pairwiseConclusions:[]};const before=JSON.stringify(d),text=renderer().render(d);assert.match(text,/历史规则/);assert.match(text,/历史原文/);assert.equal(JSON.stringify(d),before)});
test('unknown schema fails closed explicitly',()=>{assert.match(renderer().render({schemaVersion:'future'}),/暂不支持/)});
test('header date window follows trusted snapshot bounds, not old static dates',()=>{const r=renderer();assert.equal(typeof r.context.renderEvidenceWindow,'function');r.context.renderEvidenceWindow({brandDecision:{dateWindow:{start:'2026-09-01T00:00:00+08:00',end:'2026-09-09T00:00:00+08:00',endExclusive:true}},snapshot:{createdAt:'2026-09-08T10:00:00Z'}});assert.match(r.context.document.querySelector('#evidenceWindow').textContent,/2026.09.01.*2026.09.09.*不含/);assert.match(r.context.document.querySelector('#evidenceUpdated').textContent,/2026.09.08/);r.context.renderEvidenceWindow({});assert.match(r.context.document.querySelector('#evidenceWindow').textContent,/待确认/)});
test('human confirmed distinct from consensus and all untrusted strings escaped',()=>{const text=renderer().render(decision({insights:[{claimId:'i',text:'<img src=x onerror=alert(1)>',publicationStatus:'human_confirmed',humanDecisionStatus:'accepted_canonical',evidenceRefs:[{quote:'<script>',sourceUrl:'javascript:alert(1)'}]}]}));assert.match(text,/人工已确认/);assert.match(text,/&lt;img/);assert.doesNotMatch(text,/href="javascript:|<script>/)});
test('existing evidence drilldown escapes source text and rejects script URLs',()=>{const r=renderer();r.context.activeEvent={title:'标题',origin:'<img>',summary:'<script>',metrics:[],sources:[['抖','<img src=x>','<script>','javascript:alert(1)']]};r.context.evidencePanel={innerHTML:''};const start=html.indexOf('    function renderEvidence()');vm.runInContext(html.slice(start,html.indexOf('    function renderCompare()',start)),r.context);r.context.renderEvidence();assert.doesNotMatch(r.context.evidencePanel.innerHTML,/<img|<script|href="javascript:/);assert.match(r.context.evidencePanel.innerHTML,/&lt;img/)});
function bridge(){
 const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),messages=[],calls=[];
 const frame={contentWindow:{postMessage(message){messages.push(message)}},addEventListener(){}};
 const config={ownBrand:'本品',competitors:['竞品'],range:'30'},listeners={};
 const context=vm.createContext({document:{querySelector(k){return k==='#brand-penetration-frame'?frame:{classList:{contains(){return true}}}}},window:{addEventListener(type,fn){listeners[type]=fn}},URLSearchParams,console,structuredClone,Map,Set,crypto:require('node:crypto').webcrypto,activeEdition:()=> 'china',readBrandPenetrationProject:()=>config,brandPenetrationProjectFingerprint:c=>JSON.stringify(c),api:async(p,o)=>{calls.push({p,o});return context.response},brandPenetrationLoadToken:0,brandPenetrationRunToken:0});
 context.brandPenetrationSnapshotKeyword=c=>c.ownBrand;
 const start=app.indexOf('// Brand review authenticated bridge');
 assert.ok(start>=0,'authenticated bridge must exist');
 vm.runInContext(app.slice(start,app.indexOf('async function loadBrandPenetrationSnapshot',start)),context);
 return {context,frame,messages,calls,config};
}
test('date window retains non-midnight time and timezone precision',()=>{const r=renderer();r.context.renderEvidenceWindow({dateWindow:{start:'2026-09-01T10:30:00+08:00',end:'2026-09-09T11:45:20+08:00',endExclusive:true}});assert.match(r.context.document.querySelector('#evidenceWindow').textContent,/10:30:00\+08:00.*11:45:20\+08:00.*不含结束时刻/)});
test('dialog Tab and Shift Tab wrap without escaping iframe',()=>{const r=renderer();assert.equal(typeof r.context.trapReviewFocus,'function');let focused='',prevented=0;const first={getClientRects:()=>[1],focus(){focused='first'}},last={getClientRects:()=>[1],focus(){focused='last'}},dialog={open:true,querySelectorAll:()=>[first,{getClientRects:()=>[]},last]};r.context.trapReviewFocus({key:'Tab',target:last,preventDefault(){prevented++}},dialog);assert.equal(focused,'first');r.context.trapReviewFocus({key:'Tab',shiftKey:true,target:first,preventDefault(){prevented++}},dialog);assert.equal(focused,'last');r.context.trapReviewFocus({key:'Escape',target:first,preventDefault(){prevented++}},dialog);assert.equal(prevented,2)});
test('sandboxed review save uses explicit button activation, not form submission',()=>{assert.match(html,/<button type="button" id="reviewSave">/);assert.match(html,/save\.onclick=event=>/);assert.match(html,/reportValidity\(\)/)});
test('parent bridge rejects wrong window or non-opaque origin',()=>{const b=bridge();assert.equal(b.context.isBrandReviewFrameMessage({source:b.frame.contentWindow,origin:'null'}),true);assert.equal(b.context.isBrandReviewFrameMessage({source:{},origin:'null'}),false);assert.equal(b.context.isBrandReviewFrameMessage({source:b.frame.contentWindow,origin:'https://evil.test'}),false)});
test('iframe incoming requires exact parent and referrer origin',()=>{const r=renderer();assert.equal(typeof r.context.isTrustedBrandParent,'function');assert.equal(r.context.isTrustedBrandParent({source:{},origin:'null'}),false)});
test('closing after rerender returns focus to the replacement claim control',()=>{const r=renderer();let focused=false;r.context.document.querySelectorAll=()=>[{dataset:{reviewClaim:'c'},focus(){focused=true}}];assert.equal(typeof r.context.focusReviewOpener,'function');r.context.focusReviewOpener('c',{isConnected:false});assert.equal(focused,true)});
test('context invalidation hides stale cancellation control immediately',()=>{const r=renderer(),cancel={hidden:false,disabled:false,dataset:{token:'stale'}};r.context.document.querySelector=key=>key==='#cancelBrandReview'?cancel:null;r.context.clearBrandReview();assert.equal(cancel.hidden,true);assert.equal(cancel.dataset.token,'')});
test('browser verifier refuses public, production port, and absent isolated root',()=>{const verifierPath=path.join(root,'scripts/verify_brand_review_ui.js');assert.ok(fs.existsSync(verifierPath),'isolation verifier must exist');const {validateTarget}=require(verifierPath);for(const input of [{},{url:'https://mmnsh.com',testRoot:'/tmp/test'},{url:'http://127.0.0.1:8765',testRoot:'/tmp/test'},{url:'http://127.0.0.1:8894'}])assert.throws(()=>validateTarget(input));assert.throws(()=>validateTarget({url:'http://127.0.0.1:8894',testRoot:root}))});
test('verifier rejects DB symlink, hardlink and nested root symlink escape',()=>{const {validateDatabase}=require(path.join(root,'scripts/verify_brand_review_ui.js'));assert.equal(typeof validateDatabase,'function');const tmp=fs.realpathSync(fs.mkdtempSync('/tmp/mmn-brand-review-ui-test-')),outside=fs.realpathSync(fs.mkdtempSync('/tmp/mmn-brand-review-ui-other-')),target=path.join(outside,'fixture.db');fs.writeFileSync(target,'synthetic');for(const kind of ['symlink','hardlink']){const dir=fs.mkdtempSync(path.join(tmp,kind)),db=path.join(dir,'commercial_demo.db');if(kind==='symlink')fs.symlinkSync(target,db);else fs.linkSync(target,db);assert.throws(()=>validateDatabase(dir,db))}const clean=fs.mkdtempSync(path.join(tmp,'clean')),db=path.join(clean,'commercial_demo.db');fs.writeFileSync(db,'synthetic');assert.equal(validateDatabase(clean,db),db);fs.symlinkSync(outside,path.join(clean,'escape'));assert.throws(()=>validateDatabase(clean,db));});
async function integration(){
 try{
  const b=bridge(),ctx=b.context;
  ctx.result={snapshot:{id:'s1'}};ctx.config=b.config;
  ctx.response={ok:true,mode:'enabled',projectId:'p1',snapshotId:'s1',edition:'china',review:{reviewId:'r1',version:1,projectId:'p1',snapshotId:'s1',edition:'china',decision:decision()}};
  await ctx.attachBrandReview(ctx.result,ctx.config);
  assert.equal(b.messages.at(-1).type,'mmn-brand-review-context');
  const token=b.messages.at(-1).contextToken;
  ctx.request={type:'mmn-brand-review-decision',contextToken:token,expectedVersion:1,requestId:'request-1',claimId:'source',action:'accept',reason:'已核对',orgId:'evil',actorId:'evil',reviewId:'evil'};
  ctx.response={ok:true,review:{reviewId:'r1',version:2,projectId:'p1',snapshotId:'s1',edition:'china',decision:decision()}};
  await ctx.submitBrandReview(ctx.request);
  const body=JSON.parse(b.calls.at(-1).o.body);assert.equal(body.reviewId,'r1');assert.equal(body.expectedVersion,1);assert.equal(body.orgId,undefined);assert.equal(body.actorId,undefined);
  const count=b.calls.length;ctx.invalidateBrandReview();await ctx.submitBrandReview(ctx.request);assert.equal(b.calls.length,count);
  passed++;console.log('PASS canonical parent identity and invalidated context reject writes');
 }catch(e){failed++;console.error('FAIL canonical parent identity and invalidated context reject writes',e.message)}
 for(const [name,fn] of [
 ['late latest GET cannot restore invalidated context',async()=>{const b=bridge();let resolve;b.context.api=()=>new Promise(r=>resolve=r);const result={snapshot:{id:'s1'}};const pending=b.context.attachBrandReview(result,b.config);b.context.invalidateBrandReview();resolve({ok:true,mode:'enabled',projectId:'p',snapshotId:'s1',edition:'china',review:{reviewId:'r',version:1,projectId:'p',snapshotId:'s1',edition:'china',decision:decision()}});await pending;assert.equal(result.brandDecision,undefined)}],
 ['wrong snapshot or edition never gains write context',async()=>{const b=bridge();b.context.response={mode:'enabled',projectId:'p',snapshotId:'wrong',edition:'china',review:{reviewId:'r',version:1,projectId:'p',snapshotId:'wrong',edition:'china',decision:decision()}};await b.context.attachBrandReview({snapshot:{id:'s1'}},b.config);assert.equal(b.messages.length,0)}],
 ['project edits invalidate before save and navigation invalidates',async()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8');assert.match(app.slice(app.indexOf('function showPage(id)'),app.indexOf('function brandPenetrationDisplayItems')),/invalidateBrandReview/);assert.match(html,/mmn-brand-review-project-edit/)}],
 ['cancel control only forwards explicit cancellation to parent',async()=>{assert.match(html,/mmn-brand-review-cancel/);const app=fs.readFileSync(path.join(root,'app.js'),'utf8');assert.match(app,/brand-reviews\/jobs\/\$\{encodeURIComponent\(job\.jobId\)\}\/cancel/)}],
 ...[403,409].map(status=>['HTTP '+status+' disables subsequent saves',async()=>{const b=bridge();b.context.response={mode:'enabled',projectId:'p',snapshotId:'s',edition:'china',review:{reviewId:'r',version:1,projectId:'p',snapshotId:'s',edition:'china',decision:decision()}};await b.context.attachBrandReview({snapshot:{id:'s'}},b.config);const token=b.messages.at(-1).contextToken;let count=0;b.context.api=async()=>{count++;throw Object.assign(new Error('RAW PROVIDER ERROR'),{status})};const request={contextToken:token,expectedVersion:1,requestId:'req',claimId:'source',reason:'已核对',action:'accept'};await b.context.submitBrandReview(request);assert.equal(b.messages.at(-1).status,status);assert.doesNotMatch(b.messages.at(-1).message,/RAW/);await b.context.submitBrandReview({...request,requestId:'next'});assert.equal(count,1)}]),
 ['duplicate pending save and late POST cannot revive project',async()=>{const b=bridge();const review={reviewId:'r',version:1,projectId:'p',snapshotId:'s',edition:'china',decision:decision()};b.context.response={mode:'enabled',projectId:'p',snapshotId:'s',edition:'china',review};await b.context.attachBrandReview({snapshot:{id:'s'}},b.config);let resolve,count=0;b.context.api=()=>{count++;return new Promise(r=>resolve=r)};const request={contextToken:b.messages.at(-1).contextToken,expectedVersion:1,requestId:'req',claimId:'source',reason:'已核对',action:'accept'};const pending=b.context.submitBrandReview(request);await b.context.submitBrandReview(request);assert.equal(count,1);b.context.invalidateBrandReview();resolve({ok:true,review:{...review,version:2}});await pending;assert.equal(b.messages.at(-1).type,'mmn-brand-review-invalidated')}],
 ['reason limit matches server 1000 characters',async()=>{const b=bridge();b.context.response={mode:'enabled',projectId:'p',snapshotId:'s',edition:'china',review:{reviewId:'r',version:1,projectId:'p',snapshotId:'s',edition:'china',decision:decision()}};await b.context.attachBrandReview({snapshot:{id:'s'}},b.config);const before=b.calls.length;await b.context.submitBrandReview({contextToken:b.messages.at(-1).contextToken,expectedVersion:1,requestId:'req',claimId:'source',reason:'x'.repeat(1001),action:'accept'});assert.equal(b.calls.length,before);assert.match(html,/id="reviewReason" required maxlength="1000"/)}]
 ]){try{await fn();passed++;console.log('PASS',name)}catch(e){failed++;console.error('FAIL',name,e.message.slice(0,250))}}
 console.log(`${passed} passed, ${failed} failed`);if(failed)process.exitCode=1;
}
integration();
