const assert=require("node:assert/strict");
const fs=require("node:fs");
const path=require("node:path");
const root=path.join(__dirname,"..");
const html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const ui=fs.readFileSync(path.join(root,"vehicle-decision.js"),"utf8");
const css=fs.readFileSync(path.join(root,"vehicle-decision.css"),"utf8");

assert.match(html,/vehicle-decision\.css/);
assert.match(html,/vehicle-decision\.js/);
assert.match(ui,/车型全驾驶舱综合决策/);
assert.match(ui,/Evidence → Insight → Decision → Action → Result → Learning → Know-how/);
assert.match(ui,/高管摘要/);
assert.match(ui,/集团影响/);
assert.match(ui,/销量预警/);
assert.match(ui,/赛道环境/);
assert.match(ui,/政策环境/);
assert.match(ui,/传播势能/);
assert.match(ui,/平台阵地/);
assert.match(ui,/产品用户之声/);
assert.match(ui,/\/api\/vehicle-decisions\/snapshots/);
assert.match(ui,/\/api\/vehicle-decisions\/reports/);
assert.match(ui,/export\.pptx/);
assert.match(ui,/export\.md/);
assert.match(ui,/manual_required/);
assert.match(ui,/Result缺失保持为空/);
assert.match(ui,/未经人工批准不会进入正式Learning或Know-how/);
assert.match(ui,/data-decision="approved"/);
assert.match(ui,/data-decision="rejected"/);
assert.match(ui,/data-decision="needs_more_observation"/);
assert.match(ui,/aria-live="polite"/);
assert.match(ui,/addEventListener\("keydown"/);
assert.match(ui,/event\.key==="Escape"/);
assert.doesNotMatch(ui,/(Qwen|DeepSeek|Kimi|OpenAI|TikHub)/);
assert.match(css,/@media\(max-width:700px\)/);
assert.match(css,/grid-template-columns:1fr/);
assert.match(css,/overflow-wrap:anywhere/);
assert.match(css,/:focus-visible/);

console.log("vehicle decision UI contract passed");
