const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const server = fs.readFileSync(path.join(root, "server.py"), "utf8");
const scheduler = fs.readFileSync(path.join(root, "scripts", "run_scheduler.sh"), "utf8");
const ui = fs.readFileSync(path.join(root, "group-dashboard.js"), "utf8");
const groupImplicationsUi = ui.match(/function renderGroupImplications[\s\S]*?function renderExecutiveActions/)?.[0] || "";
const css = fs.readFileSync(path.join(root, "group-dashboard.css"), "utf8");
const charts = fs.readFileSync(path.join(root, "group-dashboard-charts.css"), "utf8");
const shellCss = fs.readFileSync(path.join(root, "style.css"), "utf8");

assert.match(html, /data-domestic-mode="management"/);
assert.doesNotMatch(html, /data-page="groupdashboard">集团营销看板<\/button>/);
assert.match(html, /id="management-dashboard-panel"[\s\S]*?hidden/);
assert.match(html, /id="dashboard"[\s\S]*?id="management-dashboard-panel"[\s\S]*?id="lead-dashboard-panel"[\s\S]*?class="project-strip"/);
assert.match(html, /id="group-dashboard-root"/);
assert.match(html, /group-dashboard\.css/);
assert.match(html, /group-dashboard\.js/);
assert.match(html, /lead-dashboard\.css/);
assert.match(html, /lead-dashboard\.js/);
assert.match(ui, /\/api\/group-dashboard-demo/);
assert.match(ui, /headers:typeof authHeaders==="function"\?authHeaders\(\):\{\}/);
assert.doesNotMatch(ui, /group-source-strip/);
assert.match(ui, /国内版专属看板/);
assert.match(ui, /集团市场决策简报/);
assert.doesNotMatch(ui, /ONE PAGE DEMO/);
assert.doesNotMatch(ui, /EXECUTIVE MARKET BRIEF/);
assert.doesNotMatch(ui, /group-dashboard-actions"><span/);
assert.match(ui, /brief\?\.headline/);
assert.match(ui, /executivePulseFrom/);
assert.match(ui, /weeklyRefresh\.statusLabel/);
assert.match(ui, /fetch\("\/api\/group-dashboard\/refresh-weekly",\{method:"POST"/);
assert.match(ui, /button\.textContent="正在检查"/);
assert.match(ui, /id="group-dashboard-refresh-status" aria-live="polite"/);
assert.match(ui, /当前看板继续保留上一期已发布数据/);
assert.match(ui, /pollExecutiveBriefReview/);
assert.match(ui, /brief\.reviewCompleted&&!brief\.reviewRunning/);
assert.match(ui, /const data=await load\(true,false,true\)/);
assert.match(ui, /force&&!reviewPoll&&!suppressReview\?"1":"0"/);
assert.match(server, /\/api\/group-dashboard\/refresh-weekly/);
assert.match(server, /\/api\/group-dashboard\/refresh-monthly-sales/);
assert.match(server, /monthly_sales_refresh_status/);
assert.match(scheduler, /"2 \$\{MMN_GROUP_WEEKLY_REFRESH_TIME:-00:00\}"/);
assert.match(scheduler, /MMN_GROUP_WEEKLY_RETRY_TIME:-09:00/);
assert.match(scheduler, /\^\(15\|16\|17\|18\)\$/);
assert.match(scheduler, /X-MMN-Scheduler/);
assert.match(ui, /44\.3万/);
assert.match(ui, /63\.1%/);
assert.match(ui, /把行业变化翻译成上汽的品牌判断/);
assert.doesNotMatch(ui, /7月不应继续用“总量冲刺”单一口径管理传播资源/);
assert.match(ui, /renderExecutiveFactChart/);
assert.match(ui, /executiveBrief/);
assert.match(ui, /双旗舰模型交叉验证/);
assert.match(ui, /MMN模型推论/);
assert.match(ui, /executive-inference-status/);
assert.doesNotMatch(ui, /双旗舰模型已引用同一事实包/);
assert.match(ui, /同期值按同比反算/);
assert.match(ui, /id="group-brand-select"/);
assert.match(ui, /renderGroupImplications\(data\.executiveBrief\|\|\{\}\)/);
assert.match(ui, /brief\.brandImplications/);
assert.match(ui, /detail\?\.consultingOutput/);
assert.match(ui, /consulting-output-grid/);
assert.match(ui, /consulting-evidence-ref/);
assert.match(ui, /evidenceLabels=\{E1:"市场数据",E2:"来源依据",E3:"证据边界"\}/);
assert.match(ui, /evidence-\$\{esc\(key\.toLowerCase\(\)\)\}/);
assert.match(ui, /consulting-evidence-legend/);
assert.match(ui, /aria-label="证据标签颜色说明"/);
assert.match(ui, /<h4>证据标签说明<\/h4>/);
assert.match(ui, /锁定的行业与业务数据/);
assert.match(ui, /事实来源及统计周期/);
assert.match(ui, /策略推断范围与数据缺口/);
assert.match(ui, /MECE 检查已通过/);
["核心结论","关键发现","数据证据","战略影响","行动建议"].forEach(section=>assert.match(groupImplicationsUi,new RegExp(`<h4>${section}<\\/h4>`)));
assert.doesNotMatch(groupImplicationsUi, /<h4>(Executive Conclusion|Key Findings|Evidence|Strategic Implication|Action Recommendation)<\/h4>/);
assert.match(groupImplicationsUi, /02 · 集团影响/);
assert.match(groupImplicationsUi, /双旗舰模型已交叉验证/);
assert.match(groupImplicationsUi, /全部集团重点品牌与车型使用同一已发布事实批次/);
assert.match(ui, /截至2026年7月12日 · 7月月内累计/);
assert.match(ui, /自然周 \$\{esc\(source\.naturalWeekPeriod/);
assert.doesNotMatch(groupImplicationsUi, />Consulting Output|GROUP IMPLICATIONS/);
assert.match(groupImplicationsUi, /replace\(\/\\s\*\\\[Evidence:/);
assert.match(ui, /kicker:"高管摘要"/);
assert.match(ui, /kicker:"集团影响"/);
assert.match(ui, /kicker:"销量预警"/);
assert.doesNotMatch(ui, /key:"actions",label:"本周动作",kicker:"本周动作"/);
assert.match(ui, /kicker:"赛道环境"/);
assert.match(ui, /kicker:"传播势能"/);
assert.match(ui, /kicker:"平台阵地"/);
assert.match(ui, /kicker:"产品用户之声"/);
assert.doesNotMatch(ui, /kicker:"(EXECUTIVE BRIEF|GROUP IMPLICATIONS|SALES EARLY WARNING|THIS WEEK'S MOVES|MARKET CONTEXT|COMPETITIVE MOMENTUM|CHANNEL PERFORMANCE|PRODUCT VOC)"/);
assert.doesNotMatch(groupImplicationsUi, /detail\.(summaryPoints|actionPoints|signalPoints)/);
assert.doesNotMatch(groupImplicationsUi, /<b>集团判断<\/b>|<b>传播动作<\/b>|<b>复盘信号<\/b>/);
assert.match(css, /\.consulting-output-grid/);
assert.match(css, /\.consulting-output-section/);
assert.match(css, /\.consulting-quality\.passed/);
assert.match(css, /\.consulting-evidence-ref\.evidence-e1/);
assert.match(css, /\.consulting-evidence-ref\.evidence-e2/);
assert.match(css, /\.consulting-evidence-ref\.evidence-e3/);
assert.match(css, /\.consulting-evidence-legend>ul/);
assert.match(server, /build_brand_consulting_output/);
assert.match(server, /inspect_consulting_output\(rendered\)/);
assert.match(ui, /机会放大｜优势势能正在形成/);
assert.match(ui, /重点补强｜关键认知仍需加强/);
assert.match(ui, /紧急行动｜重大认知风险需立即干预/);
assert.match(ui, /用户愿意换购/);
["智己","MG","荣威","大众","AUDI","别克","凯迪拉克","大通","五菱"].forEach(brand=>assert.match(ui,new RegExp(`brand:"${brand}"`)));
assert.doesNotMatch(ui, /集团层不宜只看总量下滑/);
assert.match(ui, /本周只推动三件事/);
assert.match(ui, /社媒与VOC仅用于传播认知/);
assert.match(ui, /cpcaauto\.com\/newslist\.php\?types=csjd&id=4272/);
assert.match(ui, /group-segment-plot/);
assert.match(ui, /width=1280,height=475,baseline=140/);
assert.match(ui, /deltaY=Math\.max\(35,y-r-15\)/);
assert.match(ui, /const saicLines=/);
assert.match(ui, /<tspan x=/);
assert.match(ui, /group-chart-frame group-segment-frame/);
assert.match(ui, /group-competitive-plot/);
assert.match(ui, /group-platform-plot/);
assert.match(ui, /group-attribute-plot/);
assert.match(ui, /root\.getBoundingClientRect\(\)\.width/);
assert.match(ui, /width:Math\.max\(minWidth,containerWidth-72\)/);
assert.match(ui, /E7X 所在销量赛道环境/);
assert.match(ui, /上汽重点车型细分市场销量失速预警/);
assert.match(ui, /月度预警按最新已发布整月销量计算/);
assert.match(ui, /暂定每月15日起检查新月份数据/);
assert.doesNotMatch(ui, /renderWarningComparison|sales-warning-comparison|懂车帝正反向关系解释|主动对比首位|反向对比首位|只解释预警，不改写销量、市场口径或预警等级/);
assert.match(ui, /头部基准达成率/);
assert.match(ui, /新能源车型排除本品后，取同尺寸×新能源市场内销量前3名竞品的销量中位数/);
assert.match(ui, /新能源包含纯电动、增程式和插电式混动/);
assert.match(ui, /非新能源车型按同尺寸×非新能源市场计算/);
assert.match(ui, /价格只用于策略校准，不参与竞品筛选或预警计算/);
assert.match(ui, /它不是市占率，也不是同比/);
assert.doesNotMatch(ui, /class="sales-warning-help"[^>]*\stitle=/);
assert.match(ui, /表内本品 · 当前销量包未匹配/);
assert.match(ui, /暂不计算预警/);
assert.match(ui, /renderSalesWarnings/);
assert.match(ui, /mmn:sales-warning-model-selected/);
assert.match(ui, /MMNVehicleContext/);
assert.match(ui, /emitWarningModelSelection/);
assert.match(ui, /MMNAttributionContext/);
assert.match(ui, /marketSales:item\.marketSales/);
assert.match(ui, /getProductEvidence/);
assert.match(ui, /attributionSalesPeriod/);
assert.match(ui, /data-warning-model/);
assert.match(ui, /data-warning-detail/);
assert.match(ui, /data-warning-series-id/);
assert.match(ui, /data-sales-history-trigger/);
assert.match(ui, /sales-history-popover/);
assert.match(css, /\.sales-warning-rows:has\(\.sales-warning-row\.history-open\)\{z-index:20\}/);
assert.match(ui, /点击看趋势/);
assert.match(ui, /细分市场前三平均/);
assert.match(ui, /segmentTop3AverageSales/);
assert.match(ui, /sales-history-benchmark-share/);
assert.match(css, /background:#e7b7c0/);
assert.match(ui, /缺少月份：/);
assert.match(ui, /未用 0 补齐/);
assert.match(ui, /懂车帝月销量榜/);
assert.match(ui, /closeSalesHistoryPopovers/);
assert.match(ui, /event\.key==="Escape"/);
assert.match(server, /attach_sales_warning_history/);
assert.match(server, /sales_warning_history\.json/);
assert.match(ui, /data-warning-context/);
assert.match(ui, /所处周期/);
assert.match(ui, /sales-warning-cycle-trigger/);
assert.match(ui, /sales-warning-cycle-popover/);
assert.match(ui, /sales-warning-cycle-close/);
assert.match(ui, /mmnSalesWarningCyclesV1/);
assert.match(ui, /persistedSalesWarningCycles/);
assert.match(ui, /mergeSalesWarningCycles/);
assert.match(ui, /data\.salesWarningCycles/);
assert.match(server, /load_sales_warning_cycles/);
assert.match(server, /save_sales_warning_cycle/);
assert.match(ui, /data-warning-cycle-value/);
assert.match(ui, /databaseCycle/);
assert.match(ui, /data-warning-cycle-source/);
assert.match(ui, /type="date"/);
assert.match(ui, /选择车型正式上市日期/);
assert.match(ui, /选择日期后，MMN按自然日计算T\+X与阶段，再由双旗舰模型交叉质检/);
assert.match(ui, /\/api\/group-dashboard\/cycle-review/);
assert.match(ui, /result\.status!=="verified"/);
assert.match(ui, /conclusion\.phaseLabel/);
assert.match(ui, /conclusion\.phaseRange/);
assert.match(ui, /data-warning-cycle-review-status/);
assert.doesNotMatch(ui, /placeholder="如 T\+3"|editableItems=items\.filter/);
assert.match(ui, /item\.marketSales/);
assert.match(ui, /item\.marketModelCount/);
assert.match(ui, /item\.segmentLabel/);
assert.match(ui, /full_segment_market/);
assert.match(ui, /summary\.method/);
assert.match(ui, /绿色≥80% · 黄色25%—80% · 红色＜25%/);
assert.match(ui, /预警闭环/);
assert.match(ui, /closeCriteria/);
assert.doesNotMatch(ui, /renderSalesWarningReviewGate/);
assert.doesNotMatch(ui, /双旗舰模型发布门/);
assert.doesNotMatch(ui, />Qwen /);
assert.doesNotMatch(ui, />DeepSeek /);
assert.match(ui, /双源销量口径 · 懂车帝 \+ 乘联会/);
assert.match(ui, /绿色<\/b>＝销量环比扩张/);
assert.match(ui, /红色<\/b>＝销量环比收缩/);
assert.match(ui, /绿色 \/ ↑<\/b>＝高于E7X全网NSR/);
assert.match(ui, /红色 \/ ↓<\/b>＝低于E7X全网NSR/);
assert.match(ui, /上汽集团 Top10 车型/);
assert.match(ui, /总榜推导/);
assert.match(ui, /overall_top10_minus_new_energy/);
assert.match(ui, /口径切换/);
assert.match(ui, /燃油采用乘联会 ICE 零售整体市场/);
assert.match(ui, /cpca_ice_retail_market/);
assert.match(ui, /全国总榜中的上汽车型/);
assert.match(ui, /懂车帝燃油榜中的上汽车型/);
assert.match(ui, /懂车帝车型榜待接入/);
assert.match(ui, /暂无可核对车型名次/);
assert.match(ui, /乘联会 ICE 零售/);
assert.match(ui, /saicRankPeriod/);
assert.match(ui, /sourceStale/);
assert.match(ui, /24小时内成功缓存/);
assert.match(server, /data\.cpcadata\.com\/api\/chartlist\?charttype=6/);
assert.match(ui, /E7X 五车传播势能：先声量，后 NSR/);
assert.match(ui, /先声量，后 NSR/);
assert.match(ui, /① 总体声量/);
assert.match(ui, /② 全网 NSR/);
assert.match(ui, /E7X 平台阵地点阵/);
assert.match(ui, /E7X 产品认知星图/);
assert.match(ui, /chartCanvas=\(minWidth,height\)/);
assert.match(ui, /chartCanvas\(1180,330\)/);
assert.match(ui, /chartCanvas\(1180,360\)/);
assert.match(ui, /chartCanvas\(1180,470\)/);
assert.match(ui, /layoutLabels/);
assert.match(ui, /minGap=31/);
assert.match(ui, /label-leader/);
assert.match(ui, /X轴｜本品认知/);
assert.match(ui, /Y轴｜相对竞争力/);
assert.match(ui, /认知待建立｜先建设/);
assert.match(ui, /领先优势｜重点放大/);
assert.match(ui, /双重风险｜优先修复/);
assert.match(ui, /对标短板｜重点追赶/);
assert.doesNotMatch(ui, />Segment 趋势/);
assert.match(ui, /data-market-dimension/);
assert.match(ui, /data-group-view/);
assert.match(ui, /data-group-panel/);
assert.match(ui, /key:"brief"[\s\S]*key:"implication"[\s\S]*key:"warning"[\s\S]*key:"market"[\s\S]*key:"competitive"[\s\S]*key:"platform"[\s\S]*key:"attribute"/);
assert.doesNotMatch(ui, /行业态势 → 集团影响 → 本周动作 → 证据下钻/);
assert.match(ui, /String\(index\+1\)\.padStart\(2,"0"\)/);
assert.match(ui, /sales-warning-scatter-zone green/);
assert.match(ui, /红区边界/);
assert.match(ui, /黄线里程碑/);
assert.match(ui, /绿区边界/);
assert.match(css, /\.sales-warning-scatter-zone\.green/);
assert.match(css, /\.sales-warning-scatter-point\.own circle/);
assert.match(css, /\.sales-warning-scatter-point:focus circle/);
assert.match(css, /\.sales-warning-scatter-zone,[^}]*pointer-events:none/);
assert.match(css, /\.sales-warning-scatter-selection/);
assert.match(ui, /data-group-view-prev/);
assert.match(ui, /data-group-view-next/);
assert.match(ui, /04 · MARKET CONTEXT/);
assert.match(ui, /05 · SALES EARLY WARNING/);
assert.match(ui, /05 · COMPETITIVE MOMENTUM/);
assert.match(ui, /06 · CHANNEL PERFORMANCE/);
assert.match(ui, /07 · PRODUCT VOC/);
assert.doesNotMatch(ui, /01 · MARKET CONTEXT|02 · COMPETITIVE MOMENTUM|03 · CHANNEL PERFORMANCE|04 · PRODUCT VOC/);
assert.match(ui, /const uiState=\{viewKey:"brief",brand:"",vehicleId:"",marketDimension:"",warningModel:"奥迪E5 Sportback",warningSeriesId:"",policyCompareModel:"",policyRegion:"上海"\}/);
assert.match(ui, /uiState\.viewKey=key/);
assert.match(ui, /uiState\.brand=brand/);
assert.match(ui, /uiState\.vehicleId=vehicleId/);
assert.match(ui, /uiState\.marketDimension=key/);
assert.match(ui, /pointerdown/);
assert.match(ui, /pointerup/);
assert.match(ui, /ArrowLeft/);
assert.match(ui, /ArrowRight/);
assert.match(app, /function setDomesticMode/);
assert.match(app, /function selectDashboardVehicleContext/);
assert.match(app, /window\.MMNVehicleContext/);
assert.match(app, /function productEvaluationSummaryDataset/);
assert.match(app, /registerProductEvaluation/);
assert.match(app, /function unavailableProductEvaluationDataset/);
assert.match(app, /function reconcileProductEvaluationBinding/);
assert.match(app, /PRODUCT_EVALUATION_UNAVAILABLE/);
assert.match(app, /productEvaluationBoundModel===model/);
assert.match(app, /registerProductEvaluationDataset\(state/);
assert.match(app, /当前已清除上一车型数据/);
assert.match(app, /reconcileProductEvaluationBinding\(\);\n render\(\)/);
assert.match(app, /summaryAttributeBenchmark/);
assert.match(app, /attributeBenchmarkLabel\|\|"竞品均值"/);
assert.match(app, /sellingPointInputModel=model/);
assert.match(app, /!models\.includes\(model\)&&!productEvaluationCatalogHas\(model\)/);
assert.match(app, /productEvaluationCatalogKey\(model\)/);
assert.match(app, /selectDashboardVehicleContext\(nextModel,\{source:"product-evaluation"\}\)/);
assert.match(ui, /registerProductEvaluation/);
assert.match(app, /mmn:vehicle-context-updated/);
assert.match(app, /leadPanel\.hidden=edition!=="china"/);
assert.match(app, /function renderModelHighlight/);
assert.match(app, /highlight_status==="model_verified"/);
assert.match(app, /managementDashboardVisible=!managementDashboardVisible/);
assert.match(app, /showPage\("dashboard"\)/);
assert.match(app, /button\[data-domestic-mode=/);
assert.match(app, /active\?"收起集团看板":"打开集团看板"/);
const managementModeFunction = app.match(/function setDomesticMode\([\s\S]*?\n\}/)?.[0] || "";
assert.doesNotMatch(managementModeFunction, /loadEditionData|resetOpportunityContextState|state\s*=|save\(/);
assert.doesNotMatch(ui, /domesticMode.*\/api\/group-dashboard-demo/);
assert.match(css, /\.group-dashboard-onepage/);
assert.match(css, /\.group-executive-hero h2\{font-family:"PingFang SC"/);
assert.match(css, /\.group-dashboard-onepage :is\(h2,h3\)\{font-family:"PingFang SC"/);
assert.doesNotMatch(css, /Songti SC|STSong|Noto Serif CJK SC/);
assert.match(css, /\.group-dashboard-onepage \.group-kpi-strip span\{font-size:12px;font-weight:950\}/);
assert.match(css, /\.group-dashboard-onepage \.group-kpi-strip strong\{font-size:28px;font-weight:950/);
assert.match(css, /\.group-view-deck/);
assert.match(css, /\.sales-warning-layout/);
assert.match(css, /\.sales-warning-row\.red/);
assert.match(css, /\.sales-warning-row\.gray/);
assert.match(css, /\.sales-warning-workflow/);
assert.doesNotMatch(css, /\.sales-warning-comparison/);
assert.match(css, /\.sales-warning-help/);
assert.match(css, /\.sales-warning-list-head span:last-child \.sales-warning-help:after/);
assert.match(css, /\.sales-warning-help:hover:after,\.sales-warning-help:focus-visible:after/);
assert.match(css, /\.sales-warning-row\.pending/);
assert.match(css, /\.sales-warning-list\.cycle-enabled \.sales-warning-list-head/);
assert.match(css, /\.sales-warning-cycle-popover/);
assert.match(css, /\.sales-warning-cycle-close\{position:absolute;top:10px;left:10px/);
assert.match(css, /\.sales-warning-list\.cycle-enabled \.sales-warning-row\{grid-template-columns:84px minmax\(0,1fr\) 180px 70px 104px/);
assert.match(css, /\.sales-warning-cycle>b\{font-family:"DIN Alternate",sans-serif;font-size:12px/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.sales-warning-list\.cycle-enabled \.sales-warning-row\{grid-template-columns:120px minmax\(0,1fr\) 252px 96px 142px/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.sales-warning-cycle>b\{font-size:19px\}/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.sales-warning-cycle>small\{font-size:11px!important\}/);
assert.match(css, /flex-direction:column/);
assert.doesNotMatch(css, /\.sales-warning-review-gate/);
assert.match(css, /管理层可读性模式/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.group-view-tabs\{grid-template-columns:repeat\(8,minmax\(120px,1fr\)\);gap:7px\}/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.group-view-tabs button\{min-height:48px[^}]*color:#000[^}]*font-size:16px[^}]*font-weight:950/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.group-view-tabs button\.active\{color:#fff\}/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.group-view-tabs button span\{font-size:12px;font-weight:950\}/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.group-board-section>header h2\{font-size:25px/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.executive-card-heading \.executive-inference-status\{max-width:180px;padding:4px 6px;font-size:8px!important/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.sales-warning-row\{min-height:66px/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.sales-warning-model b\{font-size:16px/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.sales-warning-detail-head h3\{font-size:26px/);
assert.match(ui, /<article class="risk \$\{esc\(item\.level\|\|"gray"\)\}"><span>该车型月销量<\/span>/);
assert.match(ui, /价格 × 销量全市场位置/);
assert.match(ui, /经销商起售价 \/ BaaS后车价/);
assert.match(ui, /蔚来、乐道、萤火虫按懂车帝经销商报价扣除对应BaaS电池价值后定位/);
assert.match(ui, /扣除\$\{point\.baasBrand\}BaaS电池价值/);
assert.match(ui, /一车一点 · 点击、Enter或空格键查看车型详情/);
assert.match(ui, /benchmarkAuditPeers/);
assert.match(ui, /class="sales-warning-scatter-point/);
assert.match(ui, /data-sales-warning-point/);
assert.match(ui, /sales-warning-scatter-hit/);
assert.match(ui, /tabindex="0" role="button" aria-pressed=/);
assert.match(ui, /activateScatterPoint/);
assert.match(ui, /event\.key==="Enter"\|\|event\.key===" "/);
assert.match(ui, /价格不参与预警计算/);
assert.match(css, /\.sales-warning-kpis article\.risk\.yellow\{border-top-color:#b18a2a;background:#fff9e8\}/);
assert.match(css, /\.sales-warning-kpis article\.risk\.green\{border-top-color:#278b68;background:#eef9f4\}/);
assert.match(css, /\.sales-warning-kpis article\.risk\.gray\{border-top-color:#718087;background:#f3f6f6\}/);
assert.match(css, /body\[data-domestic-mode="management"\] #group-dashboard-root \.group-view-panel>\.group-board-section\{[^}]*overflow-y:auto/);
assert.match(css, /内容型管理页使用页面自然滚动/);
assert.match(css, /#management-dashboard-panel:has\(\.group-view-panel:is\(\[data-group-panel="warning"\],\[data-group-panel="actions"\],\[data-group-panel="market"\]\)\.active\)\{height:auto;[^}]*overflow:visible/);
assert.match(css, /\.group-view-panel\[data-group-panel="warning"\]\.active \.sales-warning-layout\{flex:none;overflow:visible/);
assert.match(css, /\.group-view-panel\[data-group-panel="actions"\]\.active \.executive-action-grid\{min-height:420px;flex:none/);
assert.match(css, /05—08 图形看板统一加高/);
assert.match(css, /@media\(min-width:981px\)/);
assert.match(css, /#management-dashboard-panel:not\(\[hidden\]\):has\(\.group-view-panel:is\(\[data-group-panel="competitive"\],\[data-group-panel="platform"\],\[data-group-panel="attribute"\]\)\.active\)\{min-height:calc\(100vh - 72px\)\}/);
assert.match(css, /\.group-view-panel\[data-group-panel="market"\]\.active \.group-segment-frame\{padding-bottom:84px\}/);
assert.match(css, /管理层看板整体放大/);
assert.match(css, /#management-dashboard-panel:not\(\[hidden\]\):has\(\.group-view-panel\.active\)\{height:auto!important;min-height:calc\(100vh - 76px\);overflow:visible!important\}/);
assert.match(css, /\.group-view-panel\.active>\.group-board-section\{height:auto;min-height:720px;padding:28px 32px;overflow:visible/);
assert.match(css, /\.executive-yoy-card\{min-height:330px;padding:16px 18px/);
assert.match(css, /\.executive-yoy-card\{min-height:330px;padding:16px 18px;grid-template-columns:minmax\(0,1fr\);grid-template-areas:"label" "yoy" "chart" "note"/);
assert.match(css, /\.executive-yoy-card>span\{min-width:0;font-size:17px!important;line-height:1\.35;white-space:normal\}/);
assert.match(css, /\.executive-yoy-card>strong\{justify-self:start;font-size:18px;line-height:1\.25;white-space:nowrap\}/);
assert.match(css, /\.executive-yoy-card \.bar-value\{font-size:16px\}/);
assert.match(css, /\.executive-yoy-card \.bar-label\{font-size:13px\}/);
assert.match(ui, /<b>数据口径<\/b><span>乘联会用于行业趋势/);
assert.match(css, /\.executive-brief-grid/);
assert.match(css, /\.executive-impact-layout/);
assert.match(css, /data-group-panel="implication"\] \.executive-impact-layout\{display:flex;min-height:0;flex:1\}/);
assert.match(css, /data-group-panel="implication"\] \.executive-brand-switcher\{height:auto;min-height:0;align-self:stretch;flex:1\}/);
assert.match(css, /data-group-panel="implication"\] \.executive-brand-narrative-card\{height:100%\}/);
assert.match(css, /\.executive-brand-model-conclusion/);
assert.match(css, /\.executive-fact-charts/);
assert.match(css, /grid-template-rows:auto minmax\(90px,1fr\) auto/);
assert.doesNotMatch(css, /minmax\(150px,1fr\)/);
assert.match(css, /@media\(max-height:960px\) and \(min-width:981px\)/);
assert.match(css, /data-group-panel="brief"[^}]*executive-yoy-card[^}]*grid-template-rows:auto minmax\(90px,1fr\) auto/);
assert.match(css, /data-group-panel="brief"[^}]*executive-causal-chain li[^}]*padding:6px 8px 6px 24px/);
assert.match(ui, /vertical-bar/);
assert.match(ui, />本期</);
assert.match(ui, />同比同期</);
assert.match(ui, /executive-vehicle-action-select/);
assert.match(ui, /双旗舰模型交叉验证已通过/);
assert.match(ui, /data-action-vehicle-panel/);
assert.match(ui, /MMN推导结论/);
assert.match(css, /\.executive-brand-switcher/);
assert.match(css, /\.executive-brand-switcher select\{width:176px/);
assert.match(css, /\.executive-brand-switcher select:focus-visible\{border-color:#9a7627/);
assert.match(css, /\.executive-brand-narrative/);
assert.match(css, /data-group-panel="implication"[^}]*executive-brand-stage[^}]*flex:none/);
assert.match(css, /data-group-panel="implication"[^}]*executive-brand-panel\{height:auto/);
assert.match(css, /\.decision-state\.opportunity/);
assert.match(css, /\.decision-state\.watch/);
assert.match(css, /\.decision-state\.risk/);
assert.match(css, /\.mmn-highlight\.secondary/);
assert.match(css, /\.executive-action-grid/);
assert.match(css, /grid-template-columns:repeat\(8/);
assert.match(css, /overflow:hidden/);
assert.match(css, /data-group-panel="brief"[\s\S]*?overflow-y:auto/);
assert.match(css, /\.executive-causal-chain b\{color:#263941;font-size:15px/);
assert.match(css, /\.executive-causal-chain small\{color:#697a82;font-size:13px/);
assert.match(css, /\.executive-buffer b\{color:#263f37;font-size:15px/);
assert.doesNotMatch(shellCss, /data-domestic-mode="management"[^}]*#nav/);
assert.match(shellCss, /\.brand\{height:204px;flex-basis:204px/);
assert.match(shellCss, /\.model-judgment-card \.model-highlight/);
assert.match(charts, /\.group-star-point/);
assert.match(charts, /\.group-star-point \.delta\{fill:#46575f;font-size:16px/);
assert.match(charts, /\.group-star-point \.segment\{fill:#263840;font-size:19px/);
assert.match(charts, /\.group-star-point \.saic\{fill:#53656d;font-size:13px/);
assert.match(charts, /\.group-segment-frame \.group-chart-axis\{[^}]*font-size:13px/);
assert.match(charts, /\.group-segment-frame \.group-market-panel\{[^}]*padding-left:145px/);
assert.match(charts, /\.group-view-panel \.group-segment-frame \.group-chart-legend-explicit\{[^}]*font-size:21\.25px/);
assert.match(charts, /\.group-platform-point \.platform\{fill:#34464e;font-size:17px/);
assert.match(charts, /\.group-platform-point \.volume\{fill:#697b83;font-size:14px/);
assert.match(charts, /\.group-attribute-frame \.group-axis-guide[^}]*font-size:14px/);
assert.match(charts, /\.group-attribute-point text\{fill:#263b44;font-size:15px/);
assert.match(ui, /left=150,right=width-180,top=48,bottom=392/);
assert.match(ui, /minLabelY=top\+48,maxLabelY=bottom-42,minGap=31/);
assert.match(ui, /L \$\{labelPosition\.kneeX\} \$\{labelY\} L \$\{labelPosition\.lineEndX\} \$\{labelY\}/);
assert.match(ui, /class="halo" cx="\$\{x\}" cy="\$\{y\}" r="16"/);
assert.match(charts, /\.group-competitive-point/);
assert.match(charts, /\.group-platform-point/);
assert.match(charts, /\.group-attribute-point/);
assert.match(charts, /\.group-market-tabs/);

console.log("group dashboard UI tests passed");
