const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const html = fs.readFileSync(path.join(__dirname, "..", "index.html"), "utf8");
const app = fs.readFileSync(path.join(__dirname, "..", "app.js"), "utf8");
const css = fs.readFileSync(path.join(__dirname, "..", "style.css"), "utf8");
const douyinHot = fs.readFileSync(path.join(__dirname, "..", "douyin-hot-demo.js"), "utf8");
const douyinHotCss = fs.readFileSync(path.join(__dirname, "..", "douyin-hot-demo.css"), "utf8");
const legacyProductEvaluation = fs.readFileSync(path.join(__dirname, "..", "legacy-product-evaluation.js"), "utf8");

assert.match(html, /id="nsr-map-models"/);
assert.match(html, /id="nsr-map-legend"/);
assert.match(html, /id="nsr-map-insights"/);
assert.match(html, /src="nsr-map\.js(?:\?[^\"]*)?"/);
assert.match(html, /src="legacy-product-evaluation\.js(?:\?[^\"]*)?"/);
assert.ok(html.indexOf("legacy-product-evaluation.js")<html.indexOf("app.js"),"legacy NSR normalization must load before app initialization");
assert.match(app, /normalizeLegacyAttributeNsrDataset\(rawImportedDataset\)/);
assert.match(app, /normalizeLegacyAttributeNsrDataset\(saved\)/);
assert.match(legacyProductEvaluation, /attributeNsrDerivedFromSentimentCounts:true/);
assert.match(html, /产品评价数据入口/);
assert.match(html, /卖点机会决策台/);
assert.match(html, /id="dashboard-anchor-nav"/);
assert.match(html, /id="dashboard-competitor-intelligence"/);
assert.match(html, /id="dashboard-competitor-trend"/);
assert.match(html, /id="dashboard-t-cycle"/);
assert.match(html, /id="t-cycle-first-date"/);
assert.match(html, /id="t-cycle-t0-date"/);
assert.match(html, /id="t-cycle-assessment-date"/);
assert.match(html, /src="t-cycle\.js(?:\?[^\"]*)?"/);
assert.match(html, /src="sales-warning-cycle-context\.js(?:\?[^\"]*)?"/);
assert.match(html, /id="dashboard-selling-point-input"/);
assert.match(html, /id="selling-point-form"/);
assert.match(html, /id="selling-point-model-select"/);
assert.match(html, /上市核心车型/);
assert.match(html, /id="selling-point-panel-toggle"/);
assert.match(html, /aria-controls="selling-point-input-body"/);
assert.match(html, /id="selling-point-panel-toggle"[^>]*aria-expanded="false"[^>]*>展开<\/button>/);
assert.match(html, /id="selling-point-input-body" hidden/);
assert.match(html, /id="selling-point-decision-workbench"/);
assert.match(html, /id="selling-point-evidence"/);
assert.match(html, /id="selling-point-action"/);
assert.match(html, /id="dashboard-topic-stage" disabled/);
assert.match(html, /销售转化（T\+31～T\+90）/);
assert.match(html, /由上方T周期选择自动同步/);
assert.match(html, /href="#dashboard-t-cycle"/);
assert.match(html, /href="#selling-point-decision-workbench"/);
assert.doesNotMatch(html, /id="dashboard-evidence-cards"/);
assert.match(html, /id="dashboard-product-proof"/);
assert.match(html, /id="dashboard-strategy-choice"/);
assert.match(html, /id="dashboard-product-proof"[^>]*hidden/);
assert.match(html, /id="dashboard-strategy-choice"[^>]*hidden/);
assert.doesNotMatch(html, /href="#dashboard-strategy-choice"/);
assert.match(html, /id="app-home-button"/);
assert.doesNotMatch(html, /id="map-filters"/);
assert.doesNotMatch(html, /id="opportunity-evidence-workbench"/);
assert.doesNotMatch(html, /data-filter="待人工确认"/);
assert.match(app, /function renderDataFirstNsrMap\(/);
assert.match(app, /managementDashboardVisible&&source!=="sales-warning"/);
assert.match(app, /queueMicrotask\(\(\)=>render\(\)\)/);
assert.match(app, /MmnNsrMap\.buildDataFirstNsrMap/);
assert.match(app, /MmnNsrMap\.rankNsrLabel/);
assert.match(app, /data-nsr-map-detail/);
assert.match(app, /function nsrMapOwnDecisionItems\(/);
assert.match(app, /function nsrMapBubbleWidth\(/);
const nsrMapBubbleWidthDefinition = app.match(/function nsrMapBubbleWidth\([^\n]+/);
const nsrMapBubbleWidth = new Function(`${nsrMapBubbleWidthDefinition[0]}; return nsrMapBubbleWidth;`)();
assert.ok(nsrMapBubbleWidth("动力与操控", "对标 极氪007") <= 140, "NSR bubble collision width must track rendered compact pills instead of over-reserving space");
assert.match(app, /function nsrMapRequiredHeight\(/);
assert.match(app, /surface\.style\.height=`\$\{requiredHeight\}px`/);
assert.match(app, /本品领先/);
assert.match(app, /主要对标/);
assert.match(app, /本品第/);
assert.match(app, /coverageLabel/);
assert.doesNotMatch(app, /灰色代号仅用于识别车型/);
assert.doesNotMatch(app, /function renderDashboardDecisionBrief\(/);
assert.doesNotMatch(app, /function renderDashboardCompetitorSet\(/);
assert.match(app, /function attributeEvidenceStatus\(/);
assert.match(app, /function openSummaryAttributePopover\(/);
assert.match(app, /function renderDashboardCompetitorTrend\(/);
assert.match(app, /function renderTCyclePanel\(/);
assert.match(app, /function renderSellingPointInput\(/);
assert.match(app, /SELLING_POINT_LAUNCH_MODELS/);
assert.match(app, /function marketingModelContextKey\(/);
assert.match(app, /function syncMarketingModelCycleContext\(/);
assert.match(app, /salesWarningCycle/);
assert.match(app, /由销量预警同步/);
assert.match(app, /数据暂未刷新/);
assert.doesNotMatch(app, /isE7X\?"2026-05-08"/);
assert.match(app, /opportunityStorageValue\("mmnMarketingModelContext",marketingModelContextKey\(model\)\)/);
assert.match(app, /saveMarketingModelContext\(next,sellingPointInputModel\)/);
assert.match(app, /sellingPointInputCollapsed/);
assert.match(app, /sellingPointInputCollapsed=true/);
assert.match(app, /sellingPointInputCollapsed\?"展开":"收起"/);
assert.match(app, /function renderSellingPointDecisionWorkbench\(/);
assert.match(app, /function sellingPointCompetitorOptions\(/);
assert.match(app, /function sellingPointPlanningCompetitors\(/);
assert.match(app, /id="selling-point-active-competitor"/);
assert.match(app, /function sellingPointMarketingMatch\(/);
assert.match(app, /function uploadProductWhitepaper\(/);
assert.match(app, /id="product-whitepaper-upload"/);
assert.match(app, /上传产品白皮书PDF/);
assert.match(app, /白皮书中有/);
assert.match(app, /productPoints=productEvidence\.verified\?10:0/);
assert.match(css, /\.product-whitepaper-upload/);
assert.match(css, /\.product-whitepaper-citations/);
assert.doesNotMatch(app, /初步营销匹配度/);
assert.doesNotMatch(app, /周期数据35、NSR竞品35、战略卖点20、产品证据10/);
assert.match(app, /企业卖点映射已保存/);
assert.match(app, /决策准备度/);
assert.match(app, /三路独立洞察与综合动作/);
assert.match(app, /三路旗舰能力分析，并融合为一个MMN策略结论后写入RAG/);
assert.match(app, /MMN正在完成三路分析，并融合为一个策略结论/);
assert.match(app, /button\.disabled=true;button\.textContent="分析融合中…"/);
assert.match(app, /正反向竞争格局融合结论/);
assert.match(app, /三路分析已融合为唯一结论并写入RAG知识库/);
assert.doesNotMatch(app, /查看三路独立分析过程/);
assert.match(app, /function socialPlatformSampleStatus\(/);
assert.match(app, /本轮无有效样本/);
assert.match(app, /social-platform-empty-status/);
assert.match(css, /\.social-platform-empty-status/);
assert.match(app, /function dashboardDistinctCompetitorRows\(/);
assert.match(app, /function nullableNumber\(/);
assert.match(app, /function attributeSourceScores\(/);
assert.match(app, /较上周/);
assert.match(app, /正向序位 \/ 反向序位/);
assert.match(app, /占比相同时保留并列名次/);
assert.match(app, /本品→该车 \/ 该车→本品/);
assert.match(app, /同一周期占比完全相同时共享名次/);
assert.match(app, /positiveTieCounts/);
assert.match(app, /class="competitor-trend-chart"/);
assert.match(app, /不代表偏好、口碑或销量/);
assert.match(app, /暂无环比/);
assert.match(app, /持平/);
assert.match(app, /change>0\?"\+"/);
assert.match(app, /direction=change===null\|\|flat\?"→":change>0\?"↑":"↓"/);
assert.doesNotMatch(app, /changeText[^;]+pt/);
assert.doesNotMatch(app, /const selectedSource="all"/);
assert.doesNotMatch(app, /const share=Number\(latest\.share\)/);
assert.doesNotMatch(app, /共同对比增强/);
assert.doesNotMatch(app, /共同对比减弱/);
assert.doesNotMatch(app, /function renderDashboardEvidenceCards\(/);
assert.doesNotMatch(app, /NSR × 垂媒合并判断/);
assert.match(app, /function renderDashboardProductProof\(/);
assert.match(app, /function dashboardProductEvidenceTask\(/);
assert.match(app, /哪些结论能用，哪些需要先补证/);
assert.match(app, /下一步核验/);
assert.match(app, /function renderDashboardStrategyChoice\(/);
assert.match(app, /function persistDashboardLearningAndKnowhow\(/);
assert.match(app, /data-dashboard-learning/);
assert.match(app, /data-dashboard-knowhow/);
assert.match(app, /data-summary-attribute-model/);
assert.match(app, /平台 NSR 指纹矩阵/);
assert.match(app, /summary-nsr-matrix/);
assert.match(app, /summary-nsr-cell/);
assert.match(app, /颜色越绿，净喜好度越高/);
assert.doesNotMatch(app, /id="summary-nsr-platform"/);
assert.doesNotMatch(app, /<b>证据状态<\/b>/);
assert.doesNotMatch(app, /class="summary-attribute-status/);
assert.match(app, /function summaryAttributeOpportunityItems\(/);
assert.match(app, /function renderSummaryAttributeOpportunityMap\(/);
assert.match(app, /function renderSummaryAttributeOpportunityBoard\(/);
assert.match(app, /\$\{renderSummaryAttributeOpportunityBoard\(/);
assert.match(app, /id="summary-own-model"/);
assert.doesNotMatch(app, /本品车型固定展示/);
assert.match(app, /data-summary-attribute-item/);
assert.match(app, /data-summary-attribute-category/);
assert.match(app, /每个圆＝一个二级属性标签/);
assert.match(app, /X轴：<\/b>消费者怎么看本品这个属性/);
assert.match(app, /Y轴：<\/b>本品比竞品好还是差/);
assert.match(app, /用户评价偏负，但表现好于竞品/);
assert.match(app, /用户评价偏正，且优于竞品/);
assert.match(app, /用户评价偏负，且落后竞品/);
assert.match(app, /用户评价偏正，但落后竞品/);
assert.match(app, /action:"先建立正面认知"/);
assert.match(app, /action:"重点放大"/);
assert.match(app, /action:"优先修复"/);
assert.match(app, /action:"重点追赶"/);
assert.match(app, /大小＝与竞品 NSR 差距/);
assert.doesNotMatch(app, /大小＝策略影响度/);
assert.doesNotMatch(app, /data-summary-cluster-open/);
assert.doesNotMatch(app, /data-summary-cluster-close/);
assert.match(app, /function syncSummaryQuadrantOverflow\(/);
assert.match(app, /data-summary-quadrant-cloud/);
assert.match(app, /data-summary-quadrant-expand/);
assert.match(app, /data-summary-quadrant-collapse/);
assert.match(app, /scrollHeight/);
assert.doesNotMatch(app, /SUMMARY_ATTRIBUTE_CLUSTER_THRESHOLD/);
assert.match(app, /当前对标竞品/);
assert.match(app, /本竞品专项诊断/);
assert.match(app, /当前平台逐车型 NSR/);
assert.match(app, /领先.*%/);
assert.doesNotMatch(app, /百分点/);
assert.doesNotMatch(app, /toFixed\(1\)\}pp/);
assert.match(app, /查看NSR证据明细/);
assert.match(app, /查看完整车型对比表（数据审计）/);
assert.match(app, /大小不代表声量/);
assert.match(app, /来源冲突/);
assert.match(app, /本品与竞品属性对比/);
assert.match(app, /data-nsr-map-close/);
assert.match(app, /本品固定展示/);
assert.match(app, /function syncDashboardCompetitors\(\)\{\s*if\(isBlockedImport\(\)\)[\s\S]{0,250}if\(isSummaryImport\(\)\)/);
assert.doesNotMatch(app, /document\.querySelector\("#map-limit"\)\.onchange/);
assert.match(css, /\.nsr-map-models/);
assert.match(css, /\.nsr-map-legend/);
assert.match(css, /\.bubble\.pending/);
assert.match(css, /\.nsr-map-detail/);
assert.doesNotMatch(css, /\.dashboard-decision-brief/);
assert.doesNotMatch(css, /\.dashboard-competitor-set/);
assert.match(css, /\.summary-attribute-popover/);
assert.match(css, /\.summary-attribute-opportunity/);
assert.match(css, /\.summary-attribute-bubble-chart/);
assert.match(css, /\.summary-attribute-diagnosis/);
assert.match(css, /\.summary-attribute-quadrants/);
assert.match(css, /\.summary-attribute-opportunity-card/);
assert.match(css, /\.summary-attribute-comparison-context/);
assert.match(css, /\.summary-attribute-category-tabs/);
assert.match(css, /\.summary-quadrant-stage/);
assert.match(css, /\.summary-quadrant-bubble/);
assert.match(css, /\.summary-quadrant-cell\.strength[^{]*\{[^}]*border-left/);
assert.match(css, /\.summary-quadrant-cell\.repair[^{]*\{[^}]*border-top/);
assert.doesNotMatch(css, /\.summary-quadrant-cluster-orb/);
assert.doesNotMatch(css, /\.summary-quadrant-bubble\.cluster-center/);
assert.match(app, /summary-quadrant-cluster-preview/);
assert.match(app, /data-summary-preview-label/);
assert.doesNotMatch(app, /summary-quadrant-collapsed/);
assert.match(css, /\.summary-quadrant-cluster-preview/);
assert.match(css, /\.summary-quadrant-preview-orb/);
assert.match(css, /@media\(prefers-reduced-motion:reduce\)/);
assert.match(css, /\.summary-attribute-model-row/);
assert.match(css, /\.summary-nsr-matrix/);
assert.match(css, /\.summary-nsr-cell\.strong/);
assert.match(css, /\.summary-nsr-insight/);
assert.match(app, /function summaryPlatformNsrSources/);
assert.match(app, /summaryPlatformNsrSources\(all,state\.importQuality\?\.platformNsrSources\)/, "NSR matrix should recover observed sources when import metadata is empty or stale");
const nsrSourceDefinition = app.match(/function summaryPlatformNsrSources\([^\n]+/);
const summaryPlatformNsrSources = new Function(`${nsrSourceDefinition[0]}; return summaryPlatformNsrSources;`)();
assert.deepEqual(summaryPlatformNsrSources({ A: { "全网": 0.5, "抖音": 0.4 } }, []), ["全网", "抖音"]);
assert.deepEqual(summaryPlatformNsrSources({ A: { "抖音": 0.4, "微博": 0.3 } }, ["抖音"]), ["抖音", "微博"]);
const gapBubbleSizeDefinition = app.match(/function summaryAttributeGapBubbleSize\([^\n]+/);
assert.ok(gapBubbleSizeDefinition, "quadrant bubbles should size from the NSR competitor gap");
const summaryAttributeGapBubbleSize = new Function(`${gapBubbleSizeDefinition[0]}; return summaryAttributeGapBubbleSize;`)();
assert.equal(summaryAttributeGapBubbleSize(null), 58);
assert.equal(summaryAttributeGapBubbleSize(0), 58);
assert.equal(summaryAttributeGapBubbleSize(-0.5), summaryAttributeGapBubbleSize(0.5));
assert.ok(summaryAttributeGapBubbleSize(0.5) - summaryAttributeGapBubbleSize(0.05) >= 25, "materially different NSR gaps should produce visibly different bubbles");
assert.ok(summaryAttributeGapBubbleSize(1) <= 116);
assert.match(css, /\.dashboard-anchor-nav/);
assert.match(css, /\.dashboard-competitor-trend/);
assert.match(css, /\.t-cycle-rail/);
assert.match(css, /\.selling-point-map-card/);
assert.match(css, /\.selling-point-list[^}]*max-height/);
assert.match(css, /\.selling-point-list[^}]*overflow-y:auto/);
assert.match(css, /\.selling-point-input-panel\.collapsed/);
assert.match(css, /\.selling-point-decision-layout/);
assert.match(css, /\.selling-point-evidence-list/);
assert.match(css, /\.selling-point-readiness/);
assert.match(css, /\.dashboard-evidence-cards/);
assert.match(css, /\.dashboard-strategy-choice/);
assert.match(css, /\.dashboard-data-context \.data-dimension\{grid-column:span 1\}/);
assert.match(css, /\.dashboard-data-context \.label-dimension\{grid-column:span 2\}/);
assert.match(css, /\.app-home-button/);
assert.match(css, /#toast\{position:fixed;right:20px;bottom:76px/);
assert.match(css, /#dashboard\.active>\.model-judgment-panel\{grid-column:1\/-1/);
assert.match(css, /\.product-proof-cards/);
assert.match(css, /\.product-proof-card/);
assert.match(douyinHot, /\/api\/douyin-hot\/recognize/);
assert.match(douyinHot, /\/api\/douyin-hot\/rankings/);
assert.doesNotMatch(douyinHot, /DOUYIN AUTO PULSE · DEMO/);
assert.doesNotMatch(douyinHot, /const multipliers=/);
assert.match(douyinHot, /每日一次，同时更新24小时、7天与30天六个榜单/);
assert.match(douyinHot, /\/api\/douyin-hot\/collector\/connect/);
assert.match(douyinHot, /\/api\/douyin-hot\/collector\/sync/);
assert.match(douyinHot, /data-collector-force/);
assert.match(douyinHot, /强制刷新/);
assert.match(douyinHot, /榜单交付进度/);
assert.match(douyinHot, /登录成功/);
assert.match(douyinHot, /抓取排行榜/);
assert.match(douyinHot, /双模型分析/);
assert.match(douyinHot, /role="progressbar"/);
assert.match(douyinHot, /function entityRadar\(/);
assert.match(douyinHot, /const recognitionKey=/);
assert.match(douyinHot, /const recognitionSignature=/);
assert.match(douyinHot, /RECOGNITION_DELAY_MS=300/);
assert.match(douyinHot, /item\.transcript,item\.rank,item\.playCount/);
assert.match(douyinHot, /collector\/status\?edition=/);
assert.match(douyinHot, /JSON\.stringify\(\{edition:editionKey\(\)\}\)/);
assert.match(douyinHot, /recognitionState\[key\]\?\.signature!==signature/);
assert.match(douyinHot, /更新今日榜单/);
assert.match(douyinHot, /今日已更新/);
assert.match(douyinHot, /MMN识别已更新/);
assert.match(douyinHot, /双模型存在分歧/);
assert.match(douyinHot, /标题明确·待复核/);
assert.match(douyinHot, /进入人工核验/);
assert.match(douyinHot, /人工核验工作台/);
assert.match(douyinHot, /\/api\/douyin-hot\/manual-reviews/);
assert.match(douyinHot, /确认并进入雷达/);
assert.match(douyinHot, /人工结论具有最高优先级/);
assert.match(douyinHot, /data-manual-edit/);
assert.match(douyinHot, /人工修改/);
assert.match(douyinHot, /rankingExpanded:false/);
assert.match(douyinHot, /data-ranking-toggle/);
assert.match(douyinHot, /aria-expanded="false"/);
assert.match(douyinHot, /展开完整榜单/);
assert.match(douyinHot, /收起榜单/);
assert.match(douyinHotCss, /\.douyin-ranking-preview/);
assert.match(douyinHotCss, /\.douyin-ranking-close/);
assert.match(douyinHotCss, /\.douyin-manual-review/);
assert.match(douyinHotCss, /\.douyin-manual-edit/);
assert.match(app, /repeated\.map\(t=>`<span>\$\{escapeHtml\(t\)\}<\/span>`\)/, "sales ticker must escape external crawler text");
assert.match(css, /\.sales-marquee-track\{[^}]*animation:mmnSalesMarquee 60\.8s linear infinite/, "sales ticker should run at half of its previous speed");
assert.match(css, /\.sales-marquee:hover \.sales-marquee-track\{animation-duration:86\.8s\}/, "hovered sales ticker should preserve the same 50% slowdown");
assert.match(douyinHot, /freshCount/);
assert.match(douyinHotCss, /\.douyin-entity-radar/);
assert.match(douyinHotCss, /\.douyin-entity-status\.conflict/);

console.log("data-first cockpit ui: ok");
