const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const ui = fs.readFileSync(path.join(root, "group-dashboard.js"), "utf8");
const css = fs.readFileSync(path.join(root, "group-dashboard.css"), "utf8");
const charts = fs.readFileSync(path.join(root, "group-dashboard-charts.css"), "utf8");
const shellCss = fs.readFileSync(path.join(root, "style.css"), "utf8");

assert.match(html, /data-domestic-mode="management"/);
assert.doesNotMatch(html, /data-page="groupdashboard">集团营销看板<\/button>/);
assert.match(html, /id="management-dashboard-panel"[\s\S]*?hidden/);
assert.match(html, /id="dashboard"[\s\S]*?id="management-dashboard-panel"[\s\S]*?class="project-strip"/);
assert.match(html, /id="group-dashboard-root"/);
assert.match(html, /group-dashboard\.css/);
assert.match(html, /group-dashboard\.js/);
assert.match(ui, /\/api\/group-dashboard-demo/);
assert.match(ui, /社媒证据不等于市场需求或销量/);
assert.match(ui, /国内版专属看板/);
assert.match(ui, /group-segment-plot/);
assert.match(ui, /group-competitive-plot/);
assert.match(ui, /group-platform-plot/);
assert.match(ui, /group-attribute-plot/);
assert.match(ui, /E7X 所在赛道环境/);
assert.match(ui, /E7X 五车传播势能星图/);
assert.match(ui, /E7X 平台阵地点阵/);
assert.match(ui, /E7X 产品认知星图/);
assert.match(ui, /source\.fileName/);
assert.doesNotMatch(ui, />Segment 趋势/);
assert.match(ui, /data-market-dimension/);
assert.match(ui, /data-group-view/);
assert.match(ui, /data-group-panel/);
assert.match(ui, /data-group-view-prev/);
assert.match(ui, /data-group-view-next/);
assert.match(ui, /pointerdown/);
assert.match(ui, /pointerup/);
assert.match(ui, /ArrowLeft/);
assert.match(ui, /ArrowRight/);
assert.match(app, /function setDomesticMode/);
assert.match(app, /managementDashboardVisible=!managementDashboardVisible/);
assert.match(app, /showPage\("dashboard"\)/);
assert.match(app, /button\[data-domestic-mode=/);
assert.match(app, /active\?"收起集团看板":"打开集团看板"/);
const managementModeFunction = app.match(/function setDomesticMode\([\s\S]*?\n\}/)?.[0] || "";
assert.doesNotMatch(managementModeFunction, /loadEditionData|resetOpportunityContextState|state\s*=|save\(/);
assert.doesNotMatch(ui, /domesticMode.*\/api\/group-dashboard-demo/);
assert.match(css, /\.group-source-strip/);
assert.match(css, /\.group-dashboard-onepage/);
assert.match(css, /\.group-view-deck/);
assert.match(css, /overflow:hidden/);
assert.doesNotMatch(shellCss, /data-domestic-mode="management"[^}]*#nav/);
assert.match(shellCss, /\.brand\{height:204px;flex-basis:204px/);
assert.match(charts, /\.group-star-point/);
assert.match(charts, /\.group-competitive-point/);
assert.match(charts, /\.group-platform-point/);
assert.match(charts, /\.group-attribute-point/);
assert.match(charts, /\.group-market-tabs/);

console.log("group dashboard UI tests passed");
