const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const app = fs.readFileSync(path.join(root, "app.js"), "utf8");
const ui = fs.readFileSync(path.join(root, "group-dashboard.js"), "utf8");
const css = fs.readFileSync(path.join(root, "group-dashboard.css"), "utf8");
const charts = fs.readFileSync(path.join(root, "group-dashboard-charts.css"), "utf8");
const shellCss = fs.readFileSync(path.join(root, "style.css"), "utf8");

assert.match(html, /data-domestic-mode="management"/);
assert.doesNotMatch(html, /data-page="groupdashboard">集团营销看板<\/button>/);
assert.match(html, /id="management-dashboard-panel"[\s\S]*?hidden/);
assert.match(html, /id="dashboard"[\s\S]*?id="management-dashboard-panel"[\s\S]*?class="project-strip"/);
assert.match(html, /id="group-dashboard-root"/);
assert.match(html, /group-dashboard\.css/);
assert.match(html, /group-dashboard\.js/);
assert.match(ui, /\/api\/group-dashboard-demo/);
assert.match(ui, /headers:typeof authHeaders==="function"\?authHeaders\(\):\{\}/);
assert.doesNotMatch(ui, /group-source-strip/);
assert.match(ui, /国内版专属看板/);
assert.match(ui, /集团市场决策简报/);
assert.match(ui, /ONE PAGE DEMO/);
assert.match(ui, /市场在降温，但新能源仍在扩大结构性优势/);
assert.match(ui, /44\.3万/);
assert.match(ui, /63\.1%/);
assert.match(ui, /把行业变化翻译成上汽的品牌判断/);
assert.doesNotMatch(ui, /7月不应继续用“总量冲刺”单一口径管理传播资源/);
assert.match(ui, /renderExecutiveFactChart/);
assert.match(ui, /executiveBrief/);
assert.match(ui, /双旗舰模型交叉验证/);
assert.match(ui, /MMN模型推论/);
assert.match(ui, /executive-inference-status/);
assert.match(ui, /id="group-brand-select"/);
assert.match(ui, /集团判断/);
assert.match(ui, /传播动作/);
assert.match(ui, /复盘信号/);
["智己","MG","荣威","大众","AUDI","别克","凯迪拉克","大通","五菱"].forEach(brand=>assert.match(ui,new RegExp(`brand:"${brand}"`)));
assert.doesNotMatch(ui, /集团层不宜只看总量下滑/);
assert.match(ui, /本周只推动三件事/);
assert.match(ui, /社媒与 VOC 仅用于传播认知判断，不作为市场需求证明/);
assert.match(ui, /cpcaauto\.com\/newslist\.php/);
assert.match(ui, /group-segment-plot/);
assert.match(ui, /deltaY=Math\.max\(14,y-r-10\)/);
assert.match(ui, /group-competitive-plot/);
assert.match(ui, /group-platform-plot/);
assert.match(ui, /group-attribute-plot/);
assert.match(ui, /viewportWidth=window\.innerWidth\|\|1440/);
assert.match(ui, /width=Math\.max\(920,viewportWidth-320\)/);
assert.match(ui, /E7X 所在销量赛道环境/);
assert.match(ui, /销量口径 · 非声量 \/ NSR \/ 市场份额/);
assert.match(ui, /绿色<\/b>＝销量环比扩张/);
assert.match(ui, /红色<\/b>＝销量环比收缩/);
assert.match(ui, /绿色 \/ ↑<\/b>＝高于E7X全网NSR/);
assert.match(ui, /红色 \/ ↓<\/b>＝低于E7X全网NSR/);
assert.match(ui, /上汽集团 Top10 车型/);
assert.match(ui, /E7X 五车传播势能：先声量，后 NSR/);
assert.match(ui, /先声量，后 NSR/);
assert.match(ui, /① 总体声量/);
assert.match(ui, /② 全网 NSR/);
assert.match(ui, /E7X 平台阵地点阵/);
assert.match(ui, /E7X 产品认知星图/);
assert.match(ui, /layoutLabels/);
assert.match(ui, /minGap=22/);
assert.match(ui, /label-leader/);
assert.match(ui, /X轴｜本品认知/);
assert.match(ui, /Y轴｜相对竞争力/);
assert.match(ui, /认知待建立｜先建设/);
assert.match(ui, /领先优势｜重点放大/);
assert.match(ui, /双重风险｜优先修复/);
assert.match(ui, /对标短板｜重点追赶/);
assert.doesNotMatch(ui, />Segment 趋势/);
assert.match(ui, /data-market-dimension/);
assert.match(ui, /data-group-view/);
assert.match(ui, /data-group-panel/);
assert.match(ui, /data-group-view-prev/);
assert.match(ui, /data-group-view-next/);
assert.match(ui, /pointerdown/);
assert.match(ui, /pointerup/);
assert.match(ui, /ArrowLeft/);
assert.match(ui, /ArrowRight/);
assert.match(app, /function setDomesticMode/);
assert.match(app, /managementDashboardVisible=!managementDashboardVisible/);
assert.match(app, /showPage\("dashboard"\)/);
assert.match(app, /button\[data-domestic-mode=/);
assert.match(app, /active\?"收起集团看板":"打开集团看板"/);
const managementModeFunction = app.match(/function setDomesticMode\([\s\S]*?\n\}/)?.[0] || "";
assert.doesNotMatch(managementModeFunction, /loadEditionData|resetOpportunityContextState|state\s*=|save\(/);
assert.doesNotMatch(ui, /domesticMode.*\/api\/group-dashboard-demo/);
assert.match(css, /\.group-dashboard-onepage/);
assert.match(css, /\.group-dashboard-onepage \.group-kpi-strip span\{font-size:12px;font-weight:950\}/);
assert.match(css, /\.group-dashboard-onepage \.group-kpi-strip strong\{font-size:28px;font-weight:950/);
assert.match(css, /\.group-view-deck/);
assert.match(css, /\.executive-brief-grid/);
assert.match(css, /\.executive-impact-layout/);
assert.match(css, /\.executive-fact-charts/);
assert.match(css, /\.executive-brand-switcher/);
assert.match(css, /\.executive-brand-narrative/);
assert.match(css, /\.executive-action-grid/);
assert.match(css, /grid-template-columns:repeat\(7/);
assert.match(css, /overflow:hidden/);
assert.doesNotMatch(shellCss, /data-domestic-mode="management"[^}]*#nav/);
assert.match(shellCss, /\.brand\{height:204px;flex-basis:204px/);
assert.match(charts, /\.group-star-point/);
assert.match(charts, /\.group-star-point \.delta\{fill:#46575f;font-size:10px/);
assert.match(charts, /\.group-platform-point \.platform\{fill:#34464e;font-size:12px/);
assert.match(charts, /\.group-platform-point \.volume\{fill:#697b83;font-size:10px/);
assert.match(charts, /\.group-attribute-frame \.group-axis-guide[^}]*font-size:12px/);
assert.match(charts, /\.group-attribute-point text\{fill:#263b44;font-size:14px/);
assert.match(charts, /\.group-competitive-point/);
assert.match(charts, /\.group-platform-point/);
assert.match(charts, /\.group-attribute-point/);
assert.match(charts, /\.group-market-tabs/);

console.log("group dashboard UI tests passed");
